---
- name: Install apache server
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - httpd
   - git

- name: Copy the init script
  copy:
    src: index.html.raw
    dest: /var/www/html/index.html
    mode: 0644
  notify: restart httpd

- name: starting apache service
  service:
    name: httpd
    enabled: yes
    state: started
